### ISSUE TITLE
Is there a WordPress plugin using this code?

### ISSUE THREAD

**Issue by grafxflow** [abeMedia/shareCount#12]
Is there a WordPress plugin using this code? That can place it in a sidebar widget.
If not and I was to create one would there be any issues with that?

Plus it possible to wildcard a website and bring back the top 10?

**Comment by abeMedia** [comment]
I'm afraid there currently isn't one but feel free to make it. 
I'd appreciate a mention in the credits though :wink: 

As for the wildcard, I'm afraid that isn't possible. You could however use a cron job to add share counts for all your URLs to a database daily and then just fetch the top 10 with a simple query.
