### ISSUE TITLE
WordPress Loop

### ISSUE THREAD

**Issue by jamesduffell** [abeMedia/shareCount#13]
Is there a simple known method of using this script in a loop, so that a blog index page populated with post excerpts could also include the count?

Ta

**Comment by abeMedia** [comment]
You could just include the file in your template. Something like this:
```php
require("share_count.php");
$myurl = "http://google.com"
$sharecount = new shareCount;
$shares = $sharecount->get($myurl);
```
Then just echo out the shares like so `echo $shares->facebook`
