### ISSUE TITLE
Getting Parse and Syntax Error After Uploading The Donreach Plugin 

### ISSUE THREAD

**Issue by mustafastc** [abeMedia/shareCount#17]
Hi,

First of thank you so much for open sourcing such precious scripts and letting everyone to use it for free. This surely requires a big heart. =)

I tried uploading the plugin scripts and files on a sub-domain located at http://count.mybloggertricks.com/

I also created a separate Mysql database and changed the config.php values to 

>/* database settings - only required to track shares */
   public $db_type = 'mysql';
    public $db_host = 'localhost';
   public $db_name = 'mustafa_shares';
    public $db_user = 'mustafa_shares';
    public $db_pass = 'mypass';

But I am getting the following error on visiting the URL.

>Parse error: syntax error, unexpected ':' in /home1/mustafa/public_html/count/share_count.php on line 37

There looks to be some syntax errors in the share_count.php file. 

Am I doing something wrong. Would appreciate the slightest of help here.

**Comment by abeMedia** [comment]
Hi Mustafa,
The MySQL info was actually added when I was going to integrate logging of shares over time but the script was completely rewritten in Golang so the new features never got integrated into this version and the MySQL settings can be ignored.
As for the error, what version of PHP are you using?

**Comment by mustafastc** [comment]
The PHP System Default Version on my server is 5.4

@abeMedia If the files are correctly installed on my server - (Uploading config.php , shares_count.php, cleanup.php and index.php). Will I be able to produce the same results using:

http://shares.mybloggertricks.com/?url=http://google.com
just like it does with:

https://count.donreach.com/?url=http://google.com

Would really need help in installation steps. What values shall i change in config.php?

**Comment by abeMedia** [comment]
It appears you have an issue with permissions. Please make sure the files are set to 755.

**Comment by mustafastc** [comment]
@abeMedia I changed the permission of all files from 644 to 755 but same problem. 

Could you kindly answer my question that I asked in my last thread?

**Comment by mustafastc** [comment]
anyone there?

**Comment by mustafastc** [comment]
I was able to run your script on a local host though but I am getting results only for stumbleupon and for not for rest:

>processShares({"url":"http:\/\/9gag.com","shares":{"total":203014,"facebook":"","twitter":"","google":"","linkedin":"","pinterest":"","stumbleupon":203014,"delicious":0,"reddit":"","buffer":"","vk":""}})

I would really appreciate if you update your script. Looks like it is not updated since a year.

**Comment by abeMedia** [comment]
Hi, I just cloned the script as it is (changing no configuration values) and it worked on my box running PHP 5.5.9-1ubuntu4.13 without any problems. I can only assume it's an issue with your server.

**Comment by mustafastc** [comment]
Hi abemedia, Thank you for the response. The problem was surely with my webserver however the plugin script is quite outdated and includes chache classes that are not required. We have made some modifications to script and we will share it soon with our blog readers by attributing the credits to Donreach. Thank you for this awesome script =)

**Comment by mustafastc** [comment]
FINALLY WORKED AT : http://shares.ahmedzai.com/?url=http://9gag.com

The reason was that MOD security was blocking it. After white listing it, the script worked! :)

**Comment by abeMedia** [comment]
Excellent, I'm glad you got it working!
