### ISSUE TITLE
Wrong Google+ share counting

### ISSUE THREAD

**Issue by mskian** [abeMedia/shareCount#19]
Hey, Google+ shown the Wrong share counting 1 share count = shown 11 shares 2 shares - count as 22 shares
how to fix this?
I host this share count on Openshift

**Comment by abeMedia** [comment]
Could you send me the URL of your install and the URL you're trying to retrieve the count for?

Also, have you tried using the hosted API on [count.donreach.com](https://count.donreach.com/)? It's a whole different app to this and actively maintained.

**Comment by mskian** [comment]
count URL - http://count.mskian.com
URL we trying to retrieve the count - http://www,allwebtuts.com

share count  - http://count.mskian.com/?url=http://www.allwebtuts.com/activate-a-free-ssl-on-branded-bitly-short-domain/

**Comment by abeMedia** [comment]
Fixed

**Comment by mskian** [comment]
Thanks now Google+ counting shown the correct share counting :-)
