### ISSUE TITLE
Multiple url

### ISSUE THREAD

**Issue by merrittcarr** [abeMedia/shareCount#5]
Can it be updated to get all pages on a domain as a example
I have 8 pages that I share that I would like to get the combined share total

 var shareUrl = 'http://carrsdigital.net/';
 var shareUrl = 'http://carrsdigital.net/Dare2BeNaughty/';
 var shareUrl = 'http://carrsdigital.net/Dare2BeNaughtyBoudoir'
 var shareUrl = 'http://carrsdigital.net/DesignerArtBooks/OohLaLa/';
 var shareUrl = 'http://carrsdigital.net/DesignerArtBooks/StylusMag/';;
 var shareUrl = 'http://carrsdigital.net/DesignerArtBooks/Casablanca/';
 var shareUrl = 'http://carrsdigital.net/DesignerArtBooks/WhatIsSexxy';
 var shareUrl = 'http://carrsdigital.net/DesignerArtBooks/Leather&Lace';
 
Can you please help with this?
Thank you

**Comment by abeMedia** [comment]
You could create a loop and add them up...
