### ISSUE TITLE
site is echoed

### ISSUE THREAD

**Issue by srakl** [abeMedia/shareCount#7]
```php
	$count = new shareCount;
	$count->url = 'http://www.abc.com/';

	$obj = json_decode($count->get());
    $totalSocialShares = $obj->shares->total; //total social shares
```

this code when run, echo's my whole pages source code.

```php
public $format = 'json'; 			// 'json', 'jsonp' or 'xml'
```
how to get it to just return the json of the shares?

i did this for a fix, not sure its the right way.

i added 

```php
case "html":
				$this->format = 'html';
				//header ("Content-Type:text/xml"); 
				break;
```
to the setFormat() function

and in my config.php

```php
public $format = 'html'; 			// 'json', 'jsonp' or 'xml'
```

**Comment by abeMedia** [comment]
Hi,

Since the script was originally designed as a little standalone API that won't work. I will update it to allow it to be used as you intend if I find time at the weekend.

Providing you only want to use it with it's current functionality, why don't you use the hosted service? You can get all the shares like so:

```php
$shares = file_get_contents('https://count.donreach.com/?url=http://9gag.com/');

**Comment by abeMedia** [comment]
Hi again =)

I realised what a simple fix it would be and made some adjustments for you right away.
You can now use the class like one would assume e.g.

```php
require("share_count.php");
$count = new shareCount;
$count->url = 'http://9gag.com';
$count->format = 'xml';
echo $count->get();

Just pull the latest commit from the repo.

**Comment by abeMedia** [comment]
Hi again =)

I've made some adjustments to the script to make it more suitable for other uses than a standalone API.

Use the following code to get the shares now:

```php
$count = new shareCount;
$shares = $count->get('http://abc.com');
$total = $shares->total;
